"""init table: setting, mt5_account

Revision ID: 3b2cc15200f9
Revises: de8e45603b00
Create Date: 2026-06-02 22:12:25.717262

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b2cc15200f9"
down_revision: Union[str, Sequence[str], None] = "de8e45603b00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE "Setting" (
            "id" SERIAL NOT NULL, 
            "key" VARCHAR(50) NOT NULL, 
            "value" VARCHAR(255) NOT NULL, 
            PRIMARY KEY ("id")
        );
        CREATE INDEX "ix_Setting_id" ON "Setting" ("id");
        CREATE UNIQUE INDEX "ix_Setting_key" ON "Setting" ("key");

        CREATE TABLE "MT5Account" (
            "id" SERIAL NOT NULL, 
            "accountType" INTEGER NOT NULL DEFAULT 0, 
            "accountLogin" BIGINT NOT NULL DEFAULT 0, 
            "accountName" VARCHAR(50) NOT NULL, 
            "accountServer" VARCHAR(100) NOT NULL, 
            "accountPassword" VARCHAR(50) NOT NULL, 
            "copyMultiplier" FLOAT NOT NULL DEFAULT 1, 
            "copyMasterLogin" BIGINT NOT NULL DEFAULT 0, 
            "description" VARCHAR(255), 
            PRIMARY KEY ("id")
        );
        CREATE INDEX "ix_MT5Account_id" ON "MT5Account" ("id");
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP INDEX "ix_Setting_id";
        DROP INDEX "ix_Setting_key";
        DROP TABLE IF EXISTS "Setting";

        DROP INDEX "ix_MT5Account_id";
        DROP TABLE IF EXISTS "MT5Account";
        """
    )
    # ### end Alembic commands ###
