upstream reverse_api_mt5_mediai_vn {
    server 127.0.0.1:8000;
    # server host.docker.internal:8000;
    # server other:8889 weight=3;
    keepalive 32;
}

# upstream reverse_adminer {
#     server mps_adminer:8080;
#     keepalive 16;
# }

# upstream reverse_mongo_express {
#     server mps_mongo_express:8081;
#     keepalive 16;
# }

# upstream reverse_redis_insight {
#     server mps_redis_insight:5540;
#     keepalive 16;
# }

server {
    listen       443 ssl;
    server_name  api_mt5.mediai.vn;

    client_max_body_size 20M;

    ssl_certificate           C:/Programs/nginx/ssl/cloudflare/api_mt5.mediai.vn/cert.pem;
    ssl_certificate_key       C:/Programs/nginx/ssl/cloudflare/api_mt5.mediai.vn/key.pem;
    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers               'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options DENY;
    add_header X-XSS-Protection "1; mode=block";

    location / {
        proxy_pass http://reverse_api_mt5_mediai_vn;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Nginx-Proxy true;

        proxy_cache_bypass $http_upgrade; # Tránh cache cho kết nối websocket.
        proxy_redirect off;
    }

    server_tokens off;
}

server {
    listen        80;
    listen        [::]:80;
    server_name   api_mt5.mediai.vn;
    return        301 https://$host$request_uri;
}

# server {
#     listen      9080;
#     server_name _;

#     auth_basic           "Restricted";
#     auth_basic_user_file /etc/nginx/auth/db.htpasswd;

#     location / {
#         proxy_pass http://reverse_adminer;
#         proxy_http_version 1.1;
#         proxy_set_header Host $http_host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_redirect off;
#     }

#     server_tokens off;
# }

# server {
#     listen      9081;
#     server_name _;

#     auth_basic           "Restricted";
#     auth_basic_user_file /etc/nginx/auth/db.htpasswd;

#     location / {
#         proxy_pass http://reverse_mongo_express;
#         proxy_http_version 1.1;
#         proxy_set_header Host $http_host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_redirect off;
#     }

#     server_tokens off;
# }

# server {
#     listen      9540;
#     server_name _;

#     auth_basic           "Restricted";
#     auth_basic_user_file /etc/nginx/auth/db.htpasswd;

#     location / {
#         proxy_pass http://reverse_redis_insight;
#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection "upgrade";
#         proxy_set_header Host $http_host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_cache_bypass $http_upgrade;
#         proxy_redirect off;
#     }

#     server_tokens off;
# }
